#!/bin/bash
#
# omnipasteit - A quick script to create an entry on paste.omnirom.org
#                    
# Copyright (C) 2013 Trevor Drake
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# 
# Requirements xsel, curl and an internet connection 
#
# Usage : 
# Run omnipasteit 
# Make Selection in terminal 
# Ctrl+D to create paste
#
#
# See http://paste.omnirom.org/api for api details
#
#


echo "Select Text - Then Ctrl+D to create paste" && \
xsel -i -p && \
echo "Creating tmpfile" && \
xsel -o -p > /tmp/paste.$USER && \
echo "Creating paste" && \
curl -d private=1 -d name=$USER --data-urlencode text@/tmp/paste.$USER http://paste.omnirom.org/api/create
echo "Removing paste" && \
rm /tmp/paste.$USER
 
